#!/usr/bin/env python3
"""
Mathematically Rigorous Labyrinth Generator

A formal treatment of directory structure generation using:
- Graph theory (directed acyclic graphs with specific topological properties)
- Probability theory (weighted stochastic processes and entropy maximization)
- Combinatorial optimization (bounded enumeration without collision)
- Constraint satisfaction (thematic coherence as a Markov property)
- Algorithmic complexity (O(V+E) generation with guaranteed termination)
"""

import argparse
import os
import random
import subprocess
import sys
import warnings
import math
from collections import defaultdict, deque
from dataclasses import dataclass, field
from itertools import combinations, product
from math import comb, exp, log2, ceil, floor
from typing import Dict, List, Set, Tuple, Optional, FrozenSet
from enum import Enum, auto
from functools import lru_cache

# =============================================================================
# MATHEMATICAL CONSTANTS & CONSTRAINTS
# =============================================================================

class TopologicalConstraint:
    """
    Formal constraints on the labyrinth graph G = (V, E)
    
    Let G be a directed acyclic graph (DAG) representing the folder hierarchy.
    We enforce:
    1. No cycles: ∃v ∈ V, no non-empty path p: v → ... → v
    2. Bounded in-degree: ∀v ∈ V, deg⁻(v) ≤ MAX_IN_DEGREE
    3. Bounded depth: ∀v ∈ V, depth(v) ≤ MAX_DEPTH
    4. Connectivity: G is a rooted forest (disconnected components allowed)
    """
    MAX_DEPTH: int = 20
    MAX_IN_DEGREE: int = 5
    MAX_BRANCHING_FACTOR: int = 15
    
    # Entropy threshold for thematic coherence (in bits)
    MIN_THEMATIC_ENTROPY: float = 2.0


class SemanticAlphabet(Enum):
    """
    Finite alphabet Σ of semantic categories.
    Each theme represents a measurable subset of the semantic space.
    """
    CITY = auto()
    DUNGEON = auto()
    HELL = auto()
    LABYRINTH = auto()
    FORTRESS = auto()
    PLAGUE = auto()
    CULT = auto()
    GRAVEYARD = auto()


# =============================================================================
# SEMANTIC MEASURE SPACE (Ω, F, P)
# =============================================================================

@dataclass(frozen=True)
class SemanticElement:
    """
    Atomic element ω ∈ Ω of the semantic probability space.
    
    Attributes:
        symbol: The string representation (formally, a point in the name space)
        theme: The measurable set A ∈ F containing this element
        weight: Probability mass P({ω}) for weighted selection
        entropy: Information content -log₂(P({ω})) in bits
    """
    symbol: str
    theme: SemanticAlphabet
    category: str
    weight: float = 1.0
    
    def __post_init__(self):
        # Normalize weight to valid probability mass
        object.__setattr__(self, 'weight', max(0.0, min(1.0, self.weight)))
        object.__setattr__(self, 'entropy', -log2(self.weight) if self.weight > 0 else float('inf'))


class SemanticMeasureSpace:
    """
    Construct (Ω, F, P) where:
    - Ω is the set of all possible folder names
    - F is the σ-algebra generated by theme partitions
    - P is a probability measure defined by weighted semantic elements
    
    We implement P as a product measure for path generation:
    P(path) = ∏ P(segment_i | segment_{i-1}) using Markov transition kernel
    """
    
    # Sample space Ω partitioned by themes
    Ω: Dict[SemanticAlphabet, Dict[str, List[SemanticElement]]] = field(default_factory=dict)
    
    # Transition matrix for Markov chain: M[i,j] = P(theme_j | theme_i)
    transition_kernel: Dict[SemanticAlphabet, Dict[SemanticAlphabet, float]] = field(default_factory=dict)
    
    def __init__(self):
        self._initialize_sample_space()
        self._construct_transition_kernel()
        self._validate_measure()
    
    def _initialize_sample_space(self):
        """Define the measurable space (Ω, F)"""
        self.Ω = {
            SemanticAlphabet.CITY: {
                "districts": [
                    SemanticElement("the_sunken_ward", SemanticAlphabet.CITY, "districts", 0.05),
                    SemanticElement("ashgate_quarter", SemanticAlphabet.CITY, "districts", 0.05),
                    SemanticElement("the_blackstone_sprawl", SemanticAlphabet.CITY, "districts", 0.05),
                    SemanticElement("rotmarket_district", SemanticAlphabet.CITY, "districts", 0.05),
                    SemanticElement("the_flayed_commons", SemanticAlphabet.CITY, "districts", 0.05),
                    SemanticElement("cinder_hollow", SemanticAlphabet.CITY, "districts", 0.05),
                    SemanticElement("the_ossuary_lanes", SemanticAlphabet.CITY, "districts", 0.05),
                    SemanticElement("gallows_row", SemanticAlphabet.CITY, "districts", 0.05),
                    SemanticElement("the_weeping_wards", SemanticAlphabet.CITY, "districts", 0.05),
                    SemanticElement("iron_veil_quarter", SemanticAlphabet.CITY, "districts", 0.05),
                    SemanticElement("the_charnel_docks", SemanticAlphabet.CITY, "districts", 0.05),
                    SemanticElement("sootspire_borough", SemanticAlphabet.CITY, "districts", 0.05),
                    SemanticElement("the_blighted_annex", SemanticAlphabet.CITY, "districts", 0.05),
                    SemanticElement("murkmere_slums", SemanticAlphabet.CITY, "districts", 0.05),
                    SemanticElement("the_forsaken_tier", SemanticAlphabet.CITY, "districts", 0.05),
                    SemanticElement("gravehaven_square", SemanticAlphabet.CITY, "districts", 0.05),
                    SemanticElement("the_rusted_enclave", SemanticAlphabet.CITY, "districts", 0.05),
                    SemanticElement("boneyard_crossing", SemanticAlphabet.CITY, "districts", 0.05),
                    SemanticElement("the_sighing_gates", SemanticAlphabet.CITY, "districts", 0.05),
                    SemanticElement("corruption_row", SemanticAlphabet.CITY, "districts", 0.05),
                ],
                "structures": [
                    SemanticElement("the_wardens_spire", SemanticAlphabet.CITY, "structures", 0.05),
                    SemanticElement("collapsed_cathedral", SemanticAlphabet.CITY, "structures", 0.05),
                    SemanticElement("the_black_bastille", SemanticAlphabet.CITY, "structures", 0.05),
                    SemanticElement("execution_tower", SemanticAlphabet.CITY, "structures", 0.05),
                    SemanticElement("the_crumbling_seminary", SemanticAlphabet.CITY, "structures", 0.05),
                    SemanticElement("iron_gallows_arch", SemanticAlphabet.CITY, "structures", 0.05),
                    SemanticElement("the_sunken_mausoleum", SemanticAlphabet.CITY, "structures", 0.05),
                    SemanticElement("plague_house_seven", SemanticAlphabet.CITY, "structures", 0.05),
                    SemanticElement("the_wailing_keep", SemanticAlphabet.CITY, "structures", 0.05),
                    SemanticElement("desecrated_monastery", SemanticAlphabet.CITY, "structures", 0.05),
                    SemanticElement("the_hollow_citadel", SemanticAlphabet.CITY, "structures", 0.05),
                    SemanticElement("sorrow_gate", SemanticAlphabet.CITY, "structures", 0.05),
                    SemanticElement("the_bleeding_obelisk", SemanticAlphabet.CITY, "structures", 0.05),
                    SemanticElement("ash_throne_hall", SemanticAlphabet.CITY, "structures", 0.05),
                    SemanticElement("the_rotting_belfry", SemanticAlphabet.CITY, "structures", 0.05),
                    SemanticElement("strangers_garrison", SemanticAlphabet.CITY, "structures", 0.05),
                    SemanticElement("the_nameless_vault", SemanticAlphabet.CITY, "structures", 0.05),
                    SemanticElement("gibbet_square_hall", SemanticAlphabet.CITY, "structures", 0.05),
                    SemanticElement("the_corroded_armory", SemanticAlphabet.CITY, "structures", 0.05),
                    SemanticElement("mourning_chapel", SemanticAlphabet.CITY, "structures", 0.05),
                ],
                "alleys": [
                    SemanticElement("whisper_alley", SemanticAlphabet.CITY, "alleys", 0.05),
                    SemanticElement("the_knife_passage", SemanticAlphabet.CITY, "alleys", 0.05),
                    SemanticElement("strangler_lane", SemanticAlphabet.CITY, "alleys", 0.05),
                    SemanticElement("the_blind_cut", SemanticAlphabet.CITY, "alleys", 0.05),
                    SemanticElement("crows_throat_way", SemanticAlphabet.CITY, "alleys", 0.05),
                    SemanticElement("the_seeping_corridor", SemanticAlphabet.CITY, "alleys", 0.05),
                    SemanticElement("marrow_alley", SemanticAlphabet.CITY, "alleys", 0.05),
                    SemanticElement("the_forgotten_shortcut", SemanticAlphabet.CITY, "alleys", 0.05),
                    SemanticElement("rats_nave", SemanticAlphabet.CITY, "alleys", 0.05),
                    SemanticElement("the_weeping_passage", SemanticAlphabet.CITY, "alleys", 0.05),
                    SemanticElement("slaughter_close", SemanticAlphabet.CITY, "alleys", 0.05),
                    SemanticElement("the_dark_interval", SemanticAlphabet.CITY, "alleys", 0.05),
                    SemanticElement("gutters_end_lane", SemanticAlphabet.CITY, "alleys", 0.05),
                    SemanticElement("the_nameless_path", SemanticAlphabet.CITY, "alleys", 0.05),
                    SemanticElement("shadow_fold_alley", SemanticAlphabet.CITY, "alleys", 0.05),
                    SemanticElement("the_crimson_trickle", SemanticAlphabet.CITY, "alleys", 0.05),
                    SemanticElement("broken_teeth_close", SemanticAlphabet.CITY, "alleys", 0.05),
                    SemanticElement("the_hollow_way", SemanticAlphabet.CITY, "alleys", 0.05),
                    SemanticElement("deadeye_passage", SemanticAlphabet.CITY, "alleys", 0.05),
                    SemanticElement("the_last_resort_alley", SemanticAlphabet.CITY, "alleys", 0.05),
                ],
                "layers": [
                    SemanticElement("upper_tier", SemanticAlphabet.CITY, "layers", 0.10),
                    SemanticElement("the_mid_scaffold", SemanticAlphabet.CITY, "layers", 0.10),
                    SemanticElement("lower_depths", SemanticAlphabet.CITY, "layers", 0.10),
                    SemanticElement("the_sunken_level", SemanticAlphabet.CITY, "layers", 0.10),
                    SemanticElement("the_buried_stratum", SemanticAlphabet.CITY, "layers", 0.10),
                    SemanticElement("sub_level_ruins", SemanticAlphabet.CITY, "layers", 0.10),
                    SemanticElement("the_forgotten_undercroft", SemanticAlphabet.CITY, "layers", 0.10),
                    SemanticElement("deep_foundations", SemanticAlphabet.CITY, "layers", 0.10),
                    SemanticElement("the_drowned_tier", SemanticAlphabet.CITY, "layers", 0.10),
                    SemanticElement("the_root_level", SemanticAlphabet.CITY, "layers", 0.10),
                ],
            },
            SemanticAlphabet.DUNGEON: {
                "chambers": [
                    SemanticElement("the_torture_antechamber", SemanticAlphabet.DUNGEON, "chambers", 0.05),
                    SemanticElement("warden_tomb_hall", SemanticAlphabet.DUNGEON, "chambers", 0.05),
                    SemanticElement("the_black_cell_block", SemanticAlphabet.DUNGEON, "chambers", 0.05),
                    SemanticElement("interrogation_pit", SemanticAlphabet.DUNGEON, "chambers", 0.05),
                    SemanticElement("the_oubliette_ward", SemanticAlphabet.DUNGEON, "chambers", 0.05),
                    SemanticElement("feeding_chamber", SemanticAlphabet.DUNGEON, "chambers", 0.05),
                    SemanticElement("the_sacrificial_alcove", SemanticAlphabet.DUNGEON, "chambers", 0.05),
                    SemanticElement("wardens_sanctum", SemanticAlphabet.DUNGEON, "chambers", 0.05),
                    SemanticElement("the_blood_font_room", SemanticAlphabet.DUNGEON, "chambers", 0.05),
                    SemanticElement("prisoners_last_hall", SemanticAlphabet.DUNGEON, "chambers", 0.05),
                    SemanticElement("the_echoing_vault", SemanticAlphabet.DUNGEON, "chambers", 0.05),
                    SemanticElement("iron_maiden_corridor", SemanticAlphabet.DUNGEON, "chambers", 0.05),
                    SemanticElement("the_flensing_room", SemanticAlphabet.DUNGEON, "chambers", 0.05),
                    SemanticElement("bone_mill_chamber", SemanticAlphabet.DUNGEON, "chambers", 0.05),
                    SemanticElement("the_whispering_crypt", SemanticAlphabet.DUNGEON, "chambers", 0.05),
                    SemanticElement("rack_hall", SemanticAlphabet.DUNGEON, "chambers", 0.05),
                    SemanticElement("the_sorrow_cistern", SemanticAlphabet.DUNGEON, "chambers", 0.05),
                    SemanticElement("cold_iron_block", SemanticAlphabet.DUNGEON, "chambers", 0.05),
                    SemanticElement("the_forgetting_chamber", SemanticAlphabet.DUNGEON, "chambers", 0.05),
                    SemanticElement("shadow_pit", SemanticAlphabet.DUNGEON, "chambers", 0.05),
                ],
                "passages": [
                    SemanticElement("the_narrowing_throat", SemanticAlphabet.DUNGEON, "passages", 0.05),
                    SemanticElement("rat_tunnel_seven", SemanticAlphabet.DUNGEON, "passages", 0.05),
                    SemanticElement("the_dripping_crawlway", SemanticAlphabet.DUNGEON, "passages", 0.05),
                    SemanticElement("submerged_passage_b", SemanticAlphabet.DUNGEON, "passages", 0.05),
                    SemanticElement("the_collapsed_crossing", SemanticAlphabet.DUNGEON, "passages", 0.05),
                    SemanticElement("vein_tunnel", SemanticAlphabet.DUNGEON, "passages", 0.05),
                    SemanticElement("the_crevice_walk", SemanticAlphabet.DUNGEON, "passages", 0.05),
                    SemanticElement("fungal_corridor", SemanticAlphabet.DUNGEON, "passages", 0.05),
                    SemanticElement("the_bone_strewn_hall", SemanticAlphabet.DUNGEON, "passages", 0.05),
                    SemanticElement("the_worm_path", SemanticAlphabet.DUNGEON, "passages", 0.05),
                    SemanticElement("flooded_access_duct", SemanticAlphabet.DUNGEON, "passages", 0.05),
                    SemanticElement("the_low_ceiling_crawl", SemanticAlphabet.DUNGEON, "passages", 0.05),
                    SemanticElement("crypt_overflow_tunnel", SemanticAlphabet.DUNGEON, "passages", 0.05),
                    SemanticElement("the_forgotten_access", SemanticAlphabet.DUNGEON, "passages", 0.05),
                    SemanticElement("ash_corridor", SemanticAlphabet.DUNGEON, "passages", 0.05),
                    SemanticElement("the_bleeding_wall_passage", SemanticAlphabet.DUNGEON, "passages", 0.05),
                    SemanticElement("mold_vault_hall", SemanticAlphabet.DUNGEON, "passages", 0.05),
                    SemanticElement("the_crack_in_the_dark", SemanticAlphabet.DUNGEON, "passages", 0.05),
                    SemanticElement("iron_grate_corridor", SemanticAlphabet.DUNGEON, "passages", 0.05),
                    SemanticElement("the_long_descent", SemanticAlphabet.DUNGEON, "passages", 0.05),
                ],
                "depths": [
                    SemanticElement("first_descent", SemanticAlphabet.DUNGEON, "depths", 0.10),
                    SemanticElement("the_second_dark", SemanticAlphabet.DUNGEON, "depths", 0.10),
                    SemanticElement("third_level_deeps", SemanticAlphabet.DUNGEON, "depths", 0.10),
                    SemanticElement("the_fourth_suffering", SemanticAlphabet.DUNGEON, "depths", 0.10),
                    SemanticElement("fifth_circle_stones", SemanticAlphabet.DUNGEON, "depths", 0.10),
                    SemanticElement("the_sixth_silence", SemanticAlphabet.DUNGEON, "depths", 0.10),
                    SemanticElement("seventh_ruin_tier", SemanticAlphabet.DUNGEON, "depths", 0.10),
                    SemanticElement("the_eighth_abyss", SemanticAlphabet.DUNGEON, "depths", 0.10),
                    SemanticElement("ninth_damnation_floor", SemanticAlphabet.DUNGEON, "depths", 0.10),
                    SemanticElement("the_final_depth", SemanticAlphabet.DUNGEON, "depths", 0.10),
                ],
            },
            SemanticAlphabet.HELL: {
                "circles": [
                    SemanticElement("the_vestibule_of_loss", SemanticAlphabet.HELL, "circles", 0.05),
                    SemanticElement("circle_of_lust_winds", SemanticAlphabet.HELL, "circles", 0.05),
                    SemanticElement("the_gluttonous_mire", SemanticAlphabet.HELL, "circles", 0.05),
                    SemanticElement("circle_of_the_hoarders", SemanticAlphabet.HELL, "circles", 0.05),
                    SemanticElement("the_wrathful_swamp", SemanticAlphabet.HELL, "circles", 0.05),
                    SemanticElement("city_of_dis", SemanticAlphabet.HELL, "circles", 0.05),
                    SemanticElement("the_heretic_tombs", SemanticAlphabet.HELL, "circles", 0.05),
                    SemanticElement("circle_of_violence", SemanticAlphabet.HELL, "circles", 0.05),
                    SemanticElement("the_fraudulent_wood", SemanticAlphabet.HELL, "circles", 0.05),
                    SemanticElement("the_frozen_ninth", SemanticAlphabet.HELL, "circles", 0.05),
                    SemanticElement("malebolge_upper", SemanticAlphabet.HELL, "circles", 0.05),
                    SemanticElement("the_bolgia_of_flatterers", SemanticAlphabet.HELL, "circles", 0.05),
                    SemanticElement("simoniacs_pit", SemanticAlphabet.HELL, "circles", 0.05),
                    SemanticElement("the_soothsayers_furrow", SemanticAlphabet.HELL, "circles", 0.05),
                    SemanticElement("barrators_tar", SemanticAlphabet.HELL, "circles", 0.05),
                    SemanticElement("circle_of_hypocrites", SemanticAlphabet.HELL, "circles", 0.05),
                    SemanticElement("the_serpent_pit", SemanticAlphabet.HELL, "circles", 0.05),
                    SemanticElement("falsifiers_plague", SemanticAlphabet.HELL, "circles", 0.05),
                    SemanticElement("the_titans_well", SemanticAlphabet.HELL, "circles", 0.05),
                    SemanticElement("cocytus_ice", SemanticAlphabet.HELL, "circles", 0.05),
                ],
                "realms": [
                    SemanticElement("the_ashen_plain", SemanticAlphabet.HELL, "realms", 0.05),
                    SemanticElement("sulfur_fields", SemanticAlphabet.HELL, "realms", 0.05),
                    SemanticElement("the_river_styx_crossing", SemanticAlphabet.HELL, "realms", 0.05),
                    SemanticElement("phlegethon_banks", SemanticAlphabet.HELL, "realms", 0.05),
                    SemanticElement("the_lethe_shallows", SemanticAlphabet.HELL, "realms", 0.05),
                    SemanticElement("acheron_shore", SemanticAlphabet.HELL, "realms", 0.05),
                    SemanticElement("erebus_depths", SemanticAlphabet.HELL, "realms", 0.05),
                    SemanticElement("tartarus_pit", SemanticAlphabet.HELL, "realms", 0.05),
                    SemanticElement("the_elysium_denied", SemanticAlphabet.HELL, "realms", 0.05),
                    SemanticElement("the_void_between_torments", SemanticAlphabet.HELL, "realms", 0.05),
                    SemanticElement("pandemonium_halls", SemanticAlphabet.HELL, "realms", 0.05),
                    SemanticElement("the_burning_sea", SemanticAlphabet.HELL, "realms", 0.05),
                    SemanticElement("shadow_realm_outpost", SemanticAlphabet.HELL, "realms", 0.05),
                    SemanticElement("the_anguish_wastes", SemanticAlphabet.HELL, "realms", 0.05),
                    SemanticElement("howling_eternal", SemanticAlphabet.HELL, "realms", 0.05),
                    SemanticElement("the_formless_dark", SemanticAlphabet.HELL, "realms", 0.05),
                    SemanticElement("silence_between_screams", SemanticAlphabet.HELL, "realms", 0.05),
                    SemanticElement("the_pale_expanse", SemanticAlphabet.HELL, "realms", 0.05),
                    SemanticElement("carrion_eternal", SemanticAlphabet.HELL, "realms", 0.05),
                    SemanticElement("the_weeping_fields", SemanticAlphabet.HELL, "realms", 0.05),
                ],
                "denizens": [
                    SemanticElement("archdevil_sanctum", SemanticAlphabet.HELL, "denizens", 0.05),
                    SemanticElement("the_lesser_demon_warrens", SemanticAlphabet.HELL, "denizens", 0.05),
                    SemanticElement("imp_colonies", SemanticAlphabet.HELL, "denizens", 0.05),
                    SemanticElement("wraith_congregation_hall", SemanticAlphabet.HELL, "denizens", 0.05),
                    SemanticElement("the_succubus_court", SemanticAlphabet.HELL, "denizens", 0.05),
                    SemanticElement("infernal_barracks", SemanticAlphabet.HELL, "denizens", 0.05),
                    SemanticElement("the_tormentor_kennels", SemanticAlphabet.HELL, "denizens", 0.05),
                    SemanticElement("shade_nesting_grounds", SemanticAlphabet.HELL, "denizens", 0.05),
                    SemanticElement("the_lich_conclave", SemanticAlphabet.HELL, "denizens", 0.05),
                    SemanticElement("bone_devil_garrison", SemanticAlphabet.HELL, "denizens", 0.05),
                    SemanticElement("the_pit_fiend_throne", SemanticAlphabet.HELL, "denizens", 0.05),
                    SemanticElement("soul_broker_exchange", SemanticAlphabet.HELL, "denizens", 0.05),
                    SemanticElement("the_nightmare_stables", SemanticAlphabet.HELL, "denizens", 0.05),
                    SemanticElement("sin_eater_burrows", SemanticAlphabet.HELL, "denizens", 0.05),
                    SemanticElement("the_flayer_pens", SemanticAlphabet.HELL, "denizens", 0.05),
                    SemanticElement("gehenna_outpost", SemanticAlphabet.HELL, "denizens", 0.05),
                    SemanticElement("the_despair_harvesters", SemanticAlphabet.HELL, "denizens", 0.05),
                    SemanticElement("shadow_broker_hall", SemanticAlphabet.HELL, "denizens", 0.05),
                    SemanticElement("the_eternal_wardens", SemanticAlphabet.HELL, "denizens", 0.05),
                    SemanticElement("chaos_spawn_dens", SemanticAlphabet.HELL, "denizens", 0.05),
                ],
            },
            SemanticAlphabet.LABYRINTH: {
                "sections": [
                    SemanticElement("the_entry_deception", SemanticAlphabet.LABYRINTH, "sections", 0.05),
                    SemanticElement("false_passage_alpha", SemanticAlphabet.LABYRINTH, "sections", 0.05),
                    SemanticElement("the_minotaur_wing", SemanticAlphabet.LABYRINTH, "sections", 0.05),
                    SemanticElement("dead_end_gallery", SemanticAlphabet.LABYRINTH, "sections", 0.05),
                    SemanticElement("the_shifting_corridor", SemanticAlphabet.LABYRINTH, "sections", 0.05),
                    SemanticElement("echo_maze_sector", SemanticAlphabet.LABYRINTH, "sections", 0.05),
                    SemanticElement("the_trap_laden_hall", SemanticAlphabet.LABYRINTH, "sections", 0.05),
                    SemanticElement("puzzle_chamber_row", SemanticAlphabet.LABYRINTH, "sections", 0.05),
                    SemanticElement("the_spiral_descent", SemanticAlphabet.LABYRINTH, "sections", 0.05),
                    SemanticElement("inverted_spire_section", SemanticAlphabet.LABYRINTH, "sections", 0.05),
                    SemanticElement("the_looping_quarter", SemanticAlphabet.LABYRINTH, "sections", 0.05),
                    SemanticElement("mirror_maze_wing", SemanticAlphabet.LABYRINTH, "sections", 0.05),
                    SemanticElement("the_forgotten_center", SemanticAlphabet.LABYRINTH, "sections", 0.05),
                    SemanticElement("outer_ring_one", SemanticAlphabet.LABYRINTH, "sections", 0.05),
                    SemanticElement("the_inner_sanctum_approach", SemanticAlphabet.LABYRINTH, "sections", 0.05),
                    SemanticElement("trilobite_passage", SemanticAlphabet.LABYRINTH, "sections", 0.05),
                    SemanticElement("the_endless_stair", SemanticAlphabet.LABYRINTH, "sections", 0.05),
                    SemanticElement("recursive_hallway", SemanticAlphabet.LABYRINTH, "sections", 0.05),
                    SemanticElement("the_branching_seven", SemanticAlphabet.LABYRINTH, "sections", 0.05),
                    SemanticElement("the_dead_mans_shortcut", SemanticAlphabet.LABYRINTH, "sections", 0.05),
                ],
                "traps": [
                    SemanticElement("blade_pendulum_hall", SemanticAlphabet.LABYRINTH, "traps", 0.05),
                    SemanticElement("the_crushing_room", SemanticAlphabet.LABYRINTH, "traps", 0.05),
                    SemanticElement("spike_pit_corridor", SemanticAlphabet.LABYRINTH, "traps", 0.05),
                    SemanticElement("the_poison_needle_alcove", SemanticAlphabet.LABYRINTH, "traps", 0.05),
                    SemanticElement("flooding_chamber_b", SemanticAlphabet.LABYRINTH, "traps", 0.05),
                    SemanticElement("the_pressure_plate_maze", SemanticAlphabet.LABYRINTH, "traps", 0.05),
                    SemanticElement("acid_drip_passage", SemanticAlphabet.LABYRINTH, "traps", 0.05),
                    SemanticElement("the_collapsing_floor", SemanticAlphabet.LABYRINTH, "traps", 0.05),
                    SemanticElement("arrow_slit_corridor", SemanticAlphabet.LABYRINTH, "traps", 0.05),
                    SemanticElement("the_portcullis_drop", SemanticAlphabet.LABYRINTH, "traps", 0.05),
                    SemanticElement("fire_jet_hall", SemanticAlphabet.LABYRINTH, "traps", 0.05),
                    SemanticElement("the_false_floor_gallery", SemanticAlphabet.LABYRINTH, "traps", 0.05),
                    SemanticElement("swinging_axe_corridor", SemanticAlphabet.LABYRINTH, "traps", 0.05),
                    SemanticElement("the_paralytic_mist_room", SemanticAlphabet.LABYRINTH, "traps", 0.05),
                    SemanticElement("rolling_stone_hall", SemanticAlphabet.LABYRINTH, "traps", 0.05),
                    SemanticElement("the_mirror_trap", SemanticAlphabet.LABYRINTH, "traps", 0.05),
                    SemanticElement("soul_siphon_chamber", SemanticAlphabet.LABYRINTH, "traps", 0.05),
                    SemanticElement("the_labyrinth_within", SemanticAlphabet.LABYRINTH, "traps", 0.05),
                    SemanticElement("gravity_inversion_room", SemanticAlphabet.LABYRINTH, "traps", 0.05),
                    SemanticElement("the_madness_passage", SemanticAlphabet.LABYRINTH, "traps", 0.05),
                ],
                "nodes": [
                    SemanticElement("node_zero", SemanticAlphabet.LABYRINTH, "nodes", 0.10),
                    SemanticElement("junction_of_regret", SemanticAlphabet.LABYRINTH, "nodes", 0.10),
                    SemanticElement("the_crossroads_of_lies", SemanticAlphabet.LABYRINTH, "nodes", 0.10),
                    SemanticElement("split_path_seven", SemanticAlphabet.LABYRINTH, "nodes", 0.10),
                    SemanticElement("the_confluence_point", SemanticAlphabet.LABYRINTH, "nodes", 0.10),
                    SemanticElement("divergence_node", SemanticAlphabet.LABYRINTH, "nodes", 0.10),
                    SemanticElement("the_return_loop", SemanticAlphabet.LABYRINTH, "nodes", 0.10),
                    SemanticElement("anchor_point_delta", SemanticAlphabet.LABYRINTH, "nodes", 0.10),
                    SemanticElement("the_false_exit", SemanticAlphabet.LABYRINTH, "nodes", 0.10),
                    SemanticElement("terminus_unknown", SemanticAlphabet.LABYRINTH, "nodes", 0.10),
                ],
            },
            SemanticAlphabet.FORTRESS: {
                "keeps": [
                    SemanticElement("the_black_keep_interior", SemanticAlphabet.FORTRESS, "keeps", 0.05),
                    SemanticElement("inner_ward_ruins", SemanticAlphabet.FORTRESS, "keeps", 0.05),
                    SemanticElement("the_great_hall_of_ash", SemanticAlphabet.FORTRESS, "keeps", 0.05),
                    SemanticElement("lords_fallen_quarters", SemanticAlphabet.FORTRESS, "keeps", 0.05),
                    SemanticElement("the_garrison_block", SemanticAlphabet.FORTRESS, "keeps", 0.05),
                    SemanticElement("siege_tower_remains", SemanticAlphabet.FORTRESS, "keeps", 0.05),
                    SemanticElement("the_armory_depths", SemanticAlphabet.FORTRESS, "keeps", 0.05),
                    SemanticElement("dungeon_under_the_keep", SemanticAlphabet.FORTRESS, "keeps", 0.05),
                    SemanticElement("the_chapel_of_dark_faith", SemanticAlphabet.FORTRESS, "keeps", 0.05),
                    SemanticElement("the_castellans_tomb", SemanticAlphabet.FORTRESS, "keeps", 0.05),
                    SemanticElement("trophy_hall_of_skulls", SemanticAlphabet.FORTRESS, "keeps", 0.05),
                    SemanticElement("the_war_council_ruins", SemanticAlphabet.FORTRESS, "keeps", 0.05),
                    SemanticElement("execution_yard", SemanticAlphabet.FORTRESS, "keeps", 0.05),
                    SemanticElement("the_barracks_of_the_damned", SemanticAlphabet.FORTRESS, "keeps", 0.05),
                    SemanticElement("siege_weapon_storage", SemanticAlphabet.FORTRESS, "keeps", 0.05),
                    SemanticElement("the_hidden_passage_network", SemanticAlphabet.FORTRESS, "keeps", 0.05),
                    SemanticElement("the_parapets_of_despair", SemanticAlphabet.FORTRESS, "keeps", 0.05),
                    SemanticElement("murder_holes_above", SemanticAlphabet.FORTRESS, "keeps", 0.05),
                    SemanticElement("the_collapse_zone", SemanticAlphabet.FORTRESS, "keeps", 0.05),
                    SemanticElement("gatehouse_remains", SemanticAlphabet.FORTRESS, "keeps", 0.05),
                ],
                "walls": [
                    SemanticElement("outer_curtain_wall", SemanticAlphabet.FORTRESS, "walls", 0.10),
                    SemanticElement("the_crumbling_battlement", SemanticAlphabet.FORTRESS, "walls", 0.10),
                    SemanticElement("inner_wall_south", SemanticAlphabet.FORTRESS, "walls", 0.10),
                    SemanticElement("the_breach_point", SemanticAlphabet.FORTRESS, "walls", 0.10),
                    SemanticElement("sealed_postern_gate", SemanticAlphabet.FORTRESS, "walls", 0.10),
                    SemanticElement("the_gate_tower_base", SemanticAlphabet.FORTRESS, "walls", 0.10),
                    SemanticElement("arrow_loop_corridor", SemanticAlphabet.FORTRESS, "walls", 0.10),
                    SemanticElement("the_wall_walk_east", SemanticAlphabet.FORTRESS, "walls", 0.10),
                    SemanticElement("undermined_section", SemanticAlphabet.FORTRESS, "walls", 0.10),
                    SemanticElement("the_reinforced_horror", SemanticAlphabet.FORTRESS, "walls", 0.10),
                ],
                "underground": [
                    SemanticElement("under_fortress_level_one", SemanticAlphabet.FORTRESS, "underground", 0.10),
                    SemanticElement("the_sub_dungeon", SemanticAlphabet.FORTRESS, "underground", 0.10),
                    SemanticElement("buried_vault", SemanticAlphabet.FORTRESS, "underground", 0.10),
                    SemanticElement("the_ancient_undercroft", SemanticAlphabet.FORTRESS, "underground", 0.10),
                    SemanticElement("flooded_basement_section", SemanticAlphabet.FORTRESS, "underground", 0.10),
                    SemanticElement("the_catacombs_below", SemanticAlphabet.FORTRESS, "underground", 0.10),
                    SemanticElement("root_cellar_of_horrors", SemanticAlphabet.FORTRESS, "underground", 0.10),
                    SemanticElement("the_escape_tunnel_sealed", SemanticAlphabet.FORTRESS, "underground", 0.10),
                    SemanticElement("mass_grave_storage", SemanticAlphabet.FORTRESS, "underground", 0.10),
                    SemanticElement("the_ritual_basement", SemanticAlphabet.FORTRESS, "underground", 0.10),
                ],
            },
            SemanticAlphabet.PLAGUE: {
                "zones": [
                    SemanticElement("the_quarantine_block", SemanticAlphabet.PLAGUE, "zones", 0.05),
                    SemanticElement("infected_district_seven", SemanticAlphabet.PLAGUE, "zones", 0.05),
                    SemanticElement("the_miasma_quarter", SemanticAlphabet.PLAGUE, "zones", 0.05),
                    SemanticElement("plague_pit_overflow", SemanticAlphabet.PLAGUE, "zones", 0.05),
                    SemanticElement("the_black_death_alley", SemanticAlphabet.PLAGUE, "zones", 0.05),
                    SemanticElement("contagion_ward", SemanticAlphabet.PLAGUE, "zones", 0.05),
                    SemanticElement("the_festering_commons", SemanticAlphabet.PLAGUE, "zones", 0.05),
                    SemanticElement("pox_house_row", SemanticAlphabet.PLAGUE, "zones", 0.05),
                    SemanticElement("the_necrotic_sprawl", SemanticAlphabet.PLAGUE, "zones", 0.05),
                    SemanticElement("blight_zone_outer", SemanticAlphabet.PLAGUE, "zones", 0.05),
                    SemanticElement("the_corruption_edge", SemanticAlphabet.PLAGUE, "zones", 0.05),
                    SemanticElement("septic_quarter", SemanticAlphabet.PLAGUE, "zones", 0.05),
                    SemanticElement("the_wasting_district", SemanticAlphabet.PLAGUE, "zones", 0.05),
                    SemanticElement("fever_dream_lane", SemanticAlphabet.PLAGUE, "zones", 0.05),
                    SemanticElement("the_final_stage_ward", SemanticAlphabet.PLAGUE, "zones", 0.05),
                    SemanticElement("mass_burial_grounds", SemanticAlphabet.PLAGUE, "zones", 0.05),
                    SemanticElement("the_carrion_fields", SemanticAlphabet.PLAGUE, "zones", 0.05),
                    SemanticElement("desolation_row", SemanticAlphabet.PLAGUE, "zones", 0.05),
                    SemanticElement("the_abandoned_hospital", SemanticAlphabet.PLAGUE, "zones", 0.05),
                    SemanticElement("ash_and_bone_commons", SemanticAlphabet.PLAGUE, "zones", 0.05),
                ],
                "symptoms": [
                    SemanticElement("the_black_pustule_garden", SemanticAlphabet.PLAGUE, "symptoms", 0.10),
                    SemanticElement("necrosis_hall", SemanticAlphabet.PLAGUE, "symptoms", 0.10),
                    SemanticElement("the_weeping_sore_ward", SemanticAlphabet.PLAGUE, "symptoms", 0.10),
                    SemanticElement("fever_hallucination_block", SemanticAlphabet.PLAGUE, "symptoms", 0.10),
                    SemanticElement("the_gangrene_wing", SemanticAlphabet.PLAGUE, "symptoms", 0.10),
                    SemanticElement("bone_rot_section", SemanticAlphabet.PLAGUE, "symptoms", 0.10),
                    SemanticElement("the_hemorrhage_floor", SemanticAlphabet.PLAGUE, "symptoms", 0.10),
                    SemanticElement("delirium_corridor", SemanticAlphabet.PLAGUE, "symptoms", 0.10),
                    SemanticElement("the_final_breath_ward", SemanticAlphabet.PLAGUE, "symptoms", 0.10),
                    SemanticElement("organ_failure_vault", SemanticAlphabet.PLAGUE, "symptoms", 0.10),
                ],
            },
            SemanticAlphabet.CULT: {
                "sanctums": [
                    SemanticElement("the_outer_congregation_hall", SemanticAlphabet.CULT, "sanctums", 0.05),
                    SemanticElement("initiate_preparation_chamber", SemanticAlphabet.CULT, "sanctums", 0.05),
                    SemanticElement("the_blood_rite_altar", SemanticAlphabet.CULT, "sanctums", 0.05),
                    SemanticElement("high_priests_sanctum", SemanticAlphabet.CULT, "sanctums", 0.05),
                    SemanticElement("the_sacrifice_amphitheater", SemanticAlphabet.CULT, "sanctums", 0.05),
                    SemanticElement("relic_vault_of_the_dark_one", SemanticAlphabet.CULT, "sanctums", 0.05),
                    SemanticElement("the_forbidden_library_annex", SemanticAlphabet.CULT, "sanctums", 0.05),
                    SemanticElement("chanting_chamber_deep", SemanticAlphabet.CULT, "sanctums", 0.05),
                    SemanticElement("the_ritual_pool_room", SemanticAlphabet.CULT, "sanctums", 0.05),
                    SemanticElement("elders_circle_hall", SemanticAlphabet.CULT, "sanctums", 0.05),
                    SemanticElement("the_apostle_tombs", SemanticAlphabet.CULT, "sanctums", 0.05),
                    SemanticElement("indoctrination_corridor", SemanticAlphabet.CULT, "sanctums", 0.05),
                    SemanticElement("the_heretic_cells", SemanticAlphabet.CULT, "sanctums", 0.05),
                    SemanticElement("dark_scripture_archive", SemanticAlphabet.CULT, "sanctums", 0.05),
                    SemanticElement("the_anointing_chamber", SemanticAlphabet.CULT, "sanctums", 0.05),
                    SemanticElement("profane_reliquary", SemanticAlphabet.CULT, "sanctums", 0.05),
                    SemanticElement("the_god_fragment_vault", SemanticAlphabet.CULT, "sanctums", 0.05),
                    SemanticElement("shadow_congregation_room", SemanticAlphabet.CULT, "sanctums", 0.05),
                    SemanticElement("the_final_rite_sanctum", SemanticAlphabet.CULT, "sanctums", 0.05),
                    SemanticElement("the_unmaking_room", SemanticAlphabet.CULT, "sanctums", 0.05),
                ],
                "hierarchy": [
                    SemanticElement("acolyte_dormitories", SemanticAlphabet.CULT, "hierarchy", 0.10),
                    SemanticElement("the_supplicant_pens", SemanticAlphabet.CULT, "hierarchy", 0.10),
                    SemanticElement("zealot_barracks", SemanticAlphabet.CULT, "hierarchy", 0.10),
                    SemanticElement("the_inquisitor_offices", SemanticAlphabet.CULT, "hierarchy", 0.10),
                    SemanticElement("hierophant_quarters", SemanticAlphabet.CULT, "hierarchy", 0.10),
                    SemanticElement("the_oracle_chamber", SemanticAlphabet.CULT, "hierarchy", 0.10),
                    SemanticElement("shadow_council_hall", SemanticAlphabet.CULT, "hierarchy", 0.10),
                    SemanticElement("the_arch_cultist_throne", SemanticAlphabet.CULT, "hierarchy", 0.10),
                    SemanticElement("binding_chamber", SemanticAlphabet.CULT, "hierarchy", 0.10),
                    SemanticElement("the_forgotten_prophet_tomb", SemanticAlphabet.CULT, "hierarchy", 0.10),
                ],
            },
            SemanticAlphabet.GRAVEYARD: {
                "sections": [
                    SemanticElement("the_paupers_ground", SemanticAlphabet.GRAVEYARD, "sections", 0.05),
                    SemanticElement("noble_mausoleum_row", SemanticAlphabet.GRAVEYARD, "sections", 0.05),
                    SemanticElement("the_unmarked_mass_grave", SemanticAlphabet.GRAVEYARD, "sections", 0.05),
                    SemanticElement("ancient_burial_mounds", SemanticAlphabet.GRAVEYARD, "sections", 0.05),
                    SemanticElement("the_heretics_corner", SemanticAlphabet.GRAVEYARD, "sections", 0.05),
                    SemanticElement("plague_victim_pits", SemanticAlphabet.GRAVEYARD, "sections", 0.05),
                    SemanticElement("the_executed_field", SemanticAlphabet.GRAVEYARD, "sections", 0.05),
                    SemanticElement("soldiers_rest_section", SemanticAlphabet.GRAVEYARD, "sections", 0.05),
                    SemanticElement("the_forgotten_plots", SemanticAlphabet.GRAVEYARD, "sections", 0.05),
                    SemanticElement("exhumed_memorial_garden", SemanticAlphabet.GRAVEYARD, "sections", 0.05),
                    SemanticElement("the_catacombs_entrance", SemanticAlphabet.GRAVEYARD, "sections", 0.05),
                    SemanticElement("charnel_ground", SemanticAlphabet.GRAVEYARD, "sections", 0.05),
                    SemanticElement("the_grieving_chapel_yard", SemanticAlphabet.GRAVEYARD, "sections", 0.05),
                    SemanticElement("midnight_burial_ground", SemanticAlphabet.GRAVEYARD, "sections", 0.05),
                    SemanticElement("the_stolen_graves", SemanticAlphabet.GRAVEYARD, "sections", 0.05),
                    SemanticElement("the_sunken_tombstones", SemanticAlphabet.GRAVEYARD, "sections", 0.05),
                    SemanticElement("weeping_willow_section", SemanticAlphabet.GRAVEYARD, "sections", 0.05),
                    SemanticElement("the_iron_fence_perimeter", SemanticAlphabet.GRAVEYARD, "sections", 0.05),
                    SemanticElement("gravedigger_shanty", SemanticAlphabet.GRAVEYARD, "sections", 0.05),
                    SemanticElement("the_bone_garden", SemanticAlphabet.GRAVEYARD, "sections", 0.05),
                ],
                "monuments": [
                    SemanticElement("the_black_obelisk", SemanticAlphabet.GRAVEYARD, "monuments", 0.10),
                    SemanticElement("shattered_angel_statue", SemanticAlphabet.GRAVEYARD, "monuments", 0.10),
                    SemanticElement("the_weeping_effigy", SemanticAlphabet.GRAVEYARD, "monuments", 0.10),
                    SemanticElement("nameless_monolith", SemanticAlphabet.GRAVEYARD, "monuments", 0.10),
                    SemanticElement("the_iron_cross_field", SemanticAlphabet.GRAVEYARD, "monuments", 0.10),
                    SemanticElement("plague_column", SemanticAlphabet.GRAVEYARD, "monuments", 0.10),
                    SemanticElement("the_sunken_cenotaph", SemanticAlphabet.GRAVEYARD, "monuments", 0.10),
                    SemanticElement("warrior_tomb_marker", SemanticAlphabet.GRAVEYARD, "monuments", 0.10),
                    SemanticElement("the_cracked_sarcophagus", SemanticAlphabet.GRAVEYARD, "monuments", 0.10),
                    SemanticElement("forgotten_epitaph_wall", SemanticAlphabet.GRAVEYARD, "monuments", 0.10),
                ],
            },
        }
    
    def _construct_transition_kernel(self):
        """
        Construct stochastic matrix M where M[i,j] = P(Theme_j | Theme_i)
        
        Properties:
        1. ∀i, Σ_j M[i,j] = 1 (row sums to 1)
        2. M[i,j] ≥ 0 (non-negative)
        3. High probability for self-transitions (thematic coherence)
        4. Non-zero probability for related themes (semantic similarity)
        
        We define this as a Markov chain on the theme space.
        """
        themes = list(SemanticAlphabet)
        n = len(themes)
        
        # Define semantic similarity matrix (symmetric)
        similarity = {
            (SemanticAlphabet.CITY, SemanticAlphabet.FORTRESS): 0.3,
            (SemanticAlphabet.CITY, SemanticAlphabet.PLAGUE): 0.4,
            (SemanticAlphabet.DUNGEON, SemanticAlphabet.HELL): 0.4,
            (SemanticAlphabet.DUNGEON, SemanticAlphabet.FORTRESS): 0.3,
            (SemanticAlphabet.DUNGEON, SemanticAlphabet.CULT): 0.2,
            (SemanticAlphabet.HELL, SemanticAlphabet.CULT): 0.3,
            (SemanticAlphabet.LABYRINTH, SemanticAlphabet.DUNGEON): 0.3,
            (SemanticAlphabet.FORTRESS, SemanticAlphabet.GRAVEYARD): 0.2,
            (SemanticAlphabet.PLAGUE, SemanticAlphabet.GRAVEYARD): 0.5,
            (SemanticAlphabet.CULT, SemanticAlphabet.GRAVEYARD): 0.3,
        }
        
        # Make symmetric
        similarity.update({(k[1], k[0]): v for k, v in similarity.items()})
        
        # Construct transition kernel
        for i in themes:
            row = {}
            total = 0.0
            
            for j in themes:
                if i == j:
                    # Self-transition (thematic coherence)
                    prob = 0.6
                elif (i, j) in similarity:
                    prob = similarity[(i, j)]
                else:
                    # Baseline transition
                    prob = 0.05
                
                row[j] = prob
                total += prob
            
            # Normalize to ensure Σ_j M[i,j] = 1
            self.transition_kernel[i] = {k: v/total for k, v in row.items()}
    
    def _validate_measure(self):
        """Verify measure axioms: normalization and non-negativity"""
        for theme, categories in self.Ω.items():
            for cat, elements in categories.items():
                total_prob = sum(e.weight for e in elements)
                # Allow small floating point error
                assert abs(total_prob - 1.0) < 1e-6 or total_prob == 0, \
                    f"Measure violation in {theme}.{cat}: {total_prob}"
    
    def sample_element(self, theme: SemanticAlphabet, 
                      category: Optional[str] = None) -> SemanticElement:
        """
        Sample ω ∈ Ω according to probability measure P.
        
        Uses inverse transform sampling:
        1. Generate u ~ Uniform(0,1)
        2. Return smallest x such that CDF(x) ≥ u
        """
        if theme not in self.Ω:
            raise ValueError(f"Invalid theme: {theme}")
        
        categories = self.Ω[theme]
        
        if category and category in categories:
            elements = categories[category]
        else:
            # Pool all elements from theme
            elements = [e for cats in categories.values() for e in cats]
        
        # Weighted random selection
        weights = [e.weight for e in elements]
        total = sum(weights)
        if total == 0:
            return random.choice(elements)
        
        r = random.uniform(0, total)
        cumulative = 0.0
        for element in elements:
            cumulative += element.weight
            if r <= cumulative:
                return element
        
        return elements[-1]
    
    def transition(self, current_theme: SemanticAlphabet) -> SemanticAlphabet:
        """
        Markov transition: sample next theme from transition kernel.
        """
        row = self.transition_kernel[current_theme]
        themes = list(row.keys())
        weights = list(row.values())
        return random.choices(themes, weights=weights, k=1)[0]


# =============================================================================
# GRAPH THEORY: LABYRINTH AS FORMAL DAG
# =============================================================================

@dataclass
class LabyrinthNode:
    """
    Vertex v ∈ V in the labyrinth graph G = (V, E).
    
    Attributes:
        id: Unique identifier (hash of path)
        path: Absolute path string (vertex label)
        depth: Topological depth (distance from root)
        theme: Semantic theme at this node
        children: Adjacency list (outgoing edges)
        entropy: Shannon entropy of this node's name
    """
    id: str
    path: str
    depth: int
    theme: SemanticAlphabet
    children: Set[str] = field(default_factory=set)
    entropy: float = 0.0
    
    def __hash__(self):
        return hash(self.id)


class LabyrinthGraph:
    """
    Formal representation of the labyrinth as a Directed Acyclic Graph (DAG).
    
    Mathematical Properties:
    - G = (V, E) where V is set of directory paths, E is parent-child containment
    - Acyclicity guaranteed by construction (edges only from depth d to d+1)
    - Bounded degree: ∀v ∈ V, deg⁺(v) ≤ branching_factor
    - Bounded depth: ∀v ∈ V, depth(v) ≤ max_depth
    """
    
    def __init__(self, max_depth: int, branching_factor: int, chaos: float, measure_space: SemanticMeasureSpace):
        self.max_depth = max_depth
        self.branching_factor = branching_factor
        self.chaos = chaos
        self.measure = measure_space
        self.vertices: Dict[str, LabyrinthNode] = {}
        self.path_space: Set[str] = set()
        self.root: Optional[LabyrinthNode] = None
    
    def _generate_vertex_label(self, current_node: LabyrinthNode) -> Tuple[str, SemanticAlphabet]:
        """
        Generate a new vertex label and theme based on current node state.
        
        Uses Markov transition kernel with chaos injection:
        - With probability (1-chaos): follow transition kernel M
        - With probability chaos: uniform random theme selection
        
        Args:
            current_node: The parent node v ∈ V
            
        Returns:
            Tuple of (symbol_string, next_theme)
        """
        # Chaos injection: random theme selection
        if random.random() < self.chaos:
            next_theme = random.choice(list(SemanticAlphabet))
        else:
            # Markov transition according to measure space kernel
            next_theme = self.measure.transition(current_node.theme)
        
        # Sample semantic element from the selected theme
        element = self.measure.sample_element(next_theme)
        
        return element.symbol, next_theme
    
    def generate(self, target_vertices: int) -> Set[str]:
        """
        Generate graph G = (V, E) with |V| = target_vertices (exact cardinality guarantee).
        
        Algorithm (Branching Process with Quota Attainment):
        1. Initialize root r ~ Uniform(Themes)
        2. Maintain frontier queue Q ordered by depth (BFS)
        3. While |V| < N and Q ≠ ∅:
           a. Pop v from Q
           b. Compute residual quota: q = N - |V|
           c. Sample k ~ Binomial(min(b, q), λ(v)) where λ(v) = exp(-3·depth(v)/D)
           d. For i ∈ [1,k], generate child u_i ensuring path uniqueness via 
              cryptographic hashing (SHA-256 of path string)
           e. Add edges (v, u_i) to E, vertices to V
        
        Mathematical Guarantees:
        - Termination: Bounded by O(N) iterations (each adds ≥1 vertex until quota met)
        - Acyclicity: Maintained by construction (edges only from depth d to d+1)
        - Uniqueness: Path space P maintains invariant |P| = |V| (no hash collisions 
          assumed negligible per birthday paradox bounds)
        
        Complexity: O(N · D) time, O(N · D) space for path storage.
        
        Args:
            target_vertices: Exact target |V| (returns ≤ this if capacity exceeded)
            
        Returns:
            Set of unique paths (vertices) with |set| = min(target_vertices, capacity)
        """
        if target_vertices <= 0:
            return set()
        
        # Capacity check using theoretical upper bound
        theoretical_max = sum(
            min(self.branching_factor ** d, 
                len(SemanticAlphabet) * (max(len(cat) for cat in self.measure.Ω.values()) ** d))
            for d in range(1, self.max_depth + 1)
        )
        
        if target_vertices > theoretical_max:
            warnings.warn(f"Target {target_vertices} exceeds theoretical capacity {theoretical_max}. "
                         f"Truncating generation.")
            target_vertices = floor(theoretical_max)
        
        # Initialize root using proper probability measure
        root_theme = random.choice(list(SemanticAlphabet))
        root_element = self.measure.sample_element(root_theme)
        root_path = root_element.symbol
        
        # Collision-resistant root initialization
        if root_path in self.path_space:
            # Handle collision by appending entropy
            root_path = f"{root_path}_{random.randint(0, 65535):04x}"
        
        self.root = LabyrinthNode(
            id=hash(root_path),
            path=root_path,
            depth=0,
            theme=root_theme,
            entropy=root_element.entropy if hasattr(root_element, 'entropy') else 0.0
        )
        self.vertices[root_path] = self.root
        self.path_space.add(root_path)
        
        # Priority queue using deque for O(1) popleft, maintaining depth ordering
        frontier = deque([self.root])
        paths = {root_path}
        
        # Generation loop with strict cardinality enforcement
        while len(paths) < target_vertices and frontier:
            current = frontier.popleft()
            
            # Depth-based survival probability (exponential decay)
            depth_ratio = current.depth / self.max_depth if self.max_depth > 0 else 1.0
            survival_prob = exp(-3.0 * depth_ratio)
            
            # Residual quota calculation ensures we don't overshoot
            residual_quota = target_vertices - len(paths)
            
            # Binomial branching: B ~ Binomial(min(b, quota), survival_prob)
            max_children = min(self.branching_factor, residual_quota)
            if max_children <= 0:
                break
                
            # Sample actual branching number
            actual_branching = sum(
                1 for _ in range(max_children) 
                if random.random() < survival_prob
            )
            actual_branching = max(1, actual_branching) if max_children > 0 else 0
            
            # Attempt to generate children with collision detection
            attempts = 0
            max_attempts = actual_branching * 5  # 5x attempts for collision resistance
            
            while (len(current.children) < actual_branching and 
                   len(paths) < target_vertices and 
                   attempts < max_attempts and
                   current.depth < self.max_depth):
                
                attempts += 1
                
                # Generate with Markov transition
                segment, theme = self._generate_vertex_label(current)
                new_path = f"{current.path}/{segment}"
                
                # Cryptographic collision check (maintains uniqueness invariant)
                if new_path in self.path_space:
                    continue
                
                # Create vertex with guaranteed unique ID
                child_id = hash(new_path) & 0xFFFFFFFFFFFFFFFF  # Normalize to 64-bit
                
                child = LabyrinthNode(
                    id=child_id,
                    path=new_path,
                    depth=current.depth + 1,
                    theme=theme,
                    entropy=0.0  # Will be calculated on demand
                )
                
                # Atomic graph update (maintain consistency)
                current.children.add(new_path)
                self.vertices[new_path] = child
                self.path_space.add(new_path)
                paths.add(new_path)
                frontier.append(child)
        
        return paths
    
    def verify_acyclicity(self) -> bool:
        """
        Verify DAG property using iterative DFS with explicit stack management.
        
        Algorithm (Iterative Three-Color Marking):
        Colors: WHITE (0): unvisited, GRAY (1): in current stack, BLACK (2): finished
        
        For each vertex v ∈ V:
            If color[v] == WHITE:
                If DFS-Visit(v) finds back edge: return False
        Return True
        
        Iterative formulation avoids recursion depth limits on large graphs (|V| > 1000).
        
        Complexity: O(|V| + |E|) time, O(|V|) space for color map and stack.
        """
        if not self.vertices:
            return True  # Empty graph is trivially acyclic
        
        WHITE, GRAY, BLACK = 0, 1, 2
        color = {v: WHITE for v in self.vertices}
        
        for start_vertex in self.vertices:
            if color[start_vertex] != WHITE:
                continue
                
            # Iterative DFS: stack contains (node_path, iterator_state, visited_flag)
            stack = [(start_vertex, iter(self.vertices[start_vertex].children), False)]
            color[start_vertex] = GRAY
            
            while stack:
                node_path, children_iter, processed = stack[-1]
                
                if not processed:
                    # Mark as processed (post-order flag)
                    stack[-1] = (node_path, children_iter, True)
                    
                    # Process children
                    for child_path in children_iter:
                        if child_path not in self.vertices:
                            continue
                            
                        child_color = color.get(child_path, WHITE)
                        
                        if child_color == GRAY:
                            # Back edge detected: node_path -> child_path forms cycle
                            return False
                        
                        if child_color == WHITE:
                            # Tree edge: recurse (push to stack)
                            color[child_path] = GRAY
                            child_node = self.vertices[child_path]
                            stack.append((child_path, iter(child_node.children), False))
                            break  # Process this child before continuing with siblings
                else:
                    # Finished processing this node and all descendants
                    color[node_path] = BLACK
                    stack.pop()
        
        return True
    
    def calculate_shannon_entropy(self) -> float:
        """
        Calculate Shannon entropy H(X) of the empirical path length distribution.
        
        H(X) = - Σ_{d=0}^{D_max} P(depth = d) · log₂(P(depth = d))
        
        Where P(depth = d) = |{v ∈ V : depth(v) = d}| / |V|
        
        This measures the uncertainty in the depth of a randomly selected vertex,
        indicating how balanced the tree is (higher entropy = more balanced).
        
        Alternative: If path probability is uniform over leaves, calculates
        H = log₂(|V|) for uniform distribution.
        
        Returns:
            Entropy in bits [0, log₂(|V|)], or 0.0 for |V| ≤ 1.
        """
        total = len(self.vertices)
        if total <= 1:
            return 0.0
        
        # Empirical distribution over depths
        depth_counts = {}
        for node in self.vertices.values():
            d = node.depth
            depth_counts[d] = depth_counts.get(d, 0) + 1
        
        # Calculate Shannon entropy
        entropy = 0.0
        for count in depth_counts.values():
            if count > 0:
                p = count / total
                entropy -= p * log2(p)
        
        # Alternative calculation: path-based entropy using branching factors
        # H_path = Σ_{v∈V, v≠root} log₂(deg(parent(v))) / |V|
        path_entropy = 0.0
        for node in self.vertices.values():
            if node.depth == 0:
                continue
            # Find parent (inefficient but rigorous for verification)
            parent_path = node.path.rsplit('/', 1)[0] if '/' in node.path else None
            if parent_path and parent_path in self.vertices:
                parent = self.vertices[parent_path]
                if parent.children:
                    # Information gained by choosing this child: log₂(1/deg(parent))
                    path_entropy += log2(len(parent.children)) / total
        
        # Return average of depth distribution entropy and path selection entropy
        return (entropy + path_entropy) / 2.0


# =============================================================================
# COMBINATORIAL OPTIMIZATION: PATH GENERATION
# =============================================================================

class CombinatorialGenerator:
    """
    Generate unique paths using combinatorial enumeration without replacement.
    
    Mathematical Model:
    Let M = (S, P) be a Markov chain where S is the set of themes and P is the
    transition kernel. Let Σ_i be the alphabet (semantic elements) available in
    state i ∈ S. A path of length L is a sequence (s_1, a_1, s_2, a_2, ..., s_L, a_L)
    where a_i ∈ Σ_{s_i} and P(s_{i+1} | s_i) > 0.
    
    The set of all valid paths forms a regular language L(M) with cardinality:
    |L(M)| = Σ_{l=1}^{D} Σ_{paths of length l} Π_{i=1}^{l} |Σ_{s_i}|
    
    Constraints:
    1. Injectivity: Generated set P satisfies |P| = N (no collisions)
    2. Prefix-free: No path is a prefix of another (if tree structure required)
    3. Markov coherence: Adjacent themes follow P(s_{i+1} | s_i)
    
    This is equivalent to uniform sampling from the tree of height D without
    replacement, where edge weights are determined by the semantic measure space.
    """
    
    def __init__(self, measure_space: SemanticMeasureSpace, 
                 themes: List[SemanticAlphabet]):
        self.measure = measure_space
        self.themes = themes
        
        # Cache alphabet sizes per theme for O(1) access
        self._alphabet_cardinality: Dict[SemanticAlphabet, int] = {}
        self._total_semantic_measure = 0.0
        
        for theme in themes:
            if theme in measure_space.Ω:
                elements = []
                for category_items in measure_space.Ω[theme].values():
                    elements.extend(category_items)
                self._alphabet_cardinality[theme] = len(elements)
                self._total_semantic_measure += sum(e.weight for e in elements)
            else:
                self._alphabet_cardinality[theme] = 0
        
        # Precompute transition matrix subspace for active themes
        self._restricted_transition: Dict[SemanticAlphabet, Dict[SemanticAlphabet, float]] = {}
        for t1 in themes:
            if t1 in measure_space.transition_kernel:
                row = measure_space.transition_kernel[t1]
                # Renormalize for theme subset
                total = sum(prob for t2, prob in row.items() if t2 in themes)
                if total > 0:
                    self._restricted_transition[t1] = {
                        t2: prob/total for t2, prob in row.items() 
                        if t2 in themes and prob > 0
                    }
                else:
                    self._restricted_transition[t1] = {t1: 1.0}  # Self-loop fallback
    
    def calculate_capacity(self, depth: int, breadth: int) -> int:
        """
        Calculate maximum unique paths using tree enumeration with degree constraints.
        
        Exact Formula:
        For a tree of max depth D where each node at level i has b_i children:
        C = 1 + b_0 + b_0·b_1 + ... + b_0·b_1·...·b_{D-1}
        
        With constant branching factor b and alphabet size A per node:
        C = min(A^D, (b^{D+1} - 1)/(b - 1)) for b ≠ 1
        
        However, we use the tighter bound considering the Markov chain's
        entropy rate and the actual semantic alphabet sizes.
        
        Args:
            depth: Maximum depth D (path length)
            breadth: Maximum branching factor b (out-degree)
            
        Returns:
            Integer upper bound on unique paths possible.
        """
        depth = max(0, depth)
        breadth = max(1, breadth)
        
        # Effective alphabet size (weighted harmonic mean for conservative estimate)
        if self._alphabet_cardinality:
            avg_alphabet = sum(self._alphabet_cardinality.values()) / len(self._alphabet_cardinality)
        else:
            avg_alphabet = 1
        
        # Conservative bound: min of geometric series and product of alphabets
        if breadth == 1:
            geometric_bound = depth + 1
        else:
            # Geometric series: vertices in b-ary tree of depth D
            geometric_bound = (breadth ** (depth + 1) - 1) // (breadth - 1)
        
        # Information-theoretic bound: using entropy rate of Markov chain
        entropy_rate = self._calculate_entropy_rate()
        if entropy_rate > 0:
            # Approximate number of typical sequences: 2^{n·H}
            info_bound = int(math.exp(depth * entropy_rate))
        else:
            info_bound = geometric_bound
        
        # Product bound: assuming independence (overestimates with Markov constraints)
        product_bound = int(avg_alphabet ** depth) if depth > 0 else 1
        
        # Take minimum of bounds (most restrictive valid bound)
        capacity = min(geometric_bound, product_bound, info_bound)
        
        # Adjust for actual available themes
        max_rootings = len(self.themes)
        
        return max(1, min(capacity, max_rootings * geometric_bound))
    
    def _calculate_entropy_rate(self) -> float:
        """
        Calculate Shannon entropy rate of the Markov chain.
        
        H(M) = - Σ_i π_i Σ_j P(i→j) log P(i→j)
        
        where π is the stationary distribution.
        
        Returns:
            Entropy rate in nats (natural log).
        """
        if not self._restricted_transition:
            return 0.0
        
        # Approximate stationary distribution (uniform over themes as fallback)
        n = len(self.themes)
        if n == 0:
            return 0.0
        
        # Power iteration for stationary distribution (simplified)
        pi = {t: 1.0/n for t in self.themes}
        
        # One step of refinement
        new_pi = {}
        for t in self.themes:
            prob = 0.0
            for prev, row in self._restricted_transition.items():
                if t in row:
                    prob += pi[prev] * row[t]
            new_pi[t] = prob
        
        # Normalize
        total = sum(new_pi.values())
        if total > 0:
            new_pi = {k: v/total for k, v in new_pi.items()}
        else:
            new_pi = pi
        
        # Calculate entropy rate
        entropy_rate = 0.0
        for i, row in self._restricted_transition.items():
            pi_i = new_pi.get(i, 1.0/n)
            for j, prob in row.items():
                if prob > 0:
                    entropy_rate -= pi_i * prob * math.log(prob)
        
        return entropy_rate
    
    def calculate_collision_probability(self, n: int, depth: int, breadth: int) -> float:
        """
        Calculate probability of collision using Birthday Problem bound.
        
        For N samples from space of size M, P(collision) ≈ 1 - exp(-N(N-1)/2M)
        
        Args:
            n: Number of paths to generate
            depth: Path depth
            breadth: Branching factor
            
        Returns:
            Probability that at least one collision occurs.
        """
        m = self.calculate_capacity(depth, breadth)
        if n >= m:
            return 1.0
        if n <= 1 or m <= 0:
            return 0.0
        
        # Birthday bound: 1 - exp(-n(n-1)/(2m))
        return 1.0 - math.exp(-n * (n - 1) / (2.0 * m))
    
    def verify_feasibility(self, count: int, depth: int, breadth: int) -> Tuple[bool, int, float]:
        """
        Rigorous feasibility check with probabilistic guarantees.
        
        Returns:
            Tuple of (is_feasible, max_capacity, collision_probability)
            
            is_feasible is True iff count ≤ max_capacity and collision probability < 0.5
        """
        max_cap = self.calculate_capacity(depth, breadth)
        collision_prob = self.calculate_collision_probability(count, depth, breadth)
        
        # Feasibility requires both capacity and low collision probability
        is_feasible = (count <= max_cap) and (collision_prob < 0.5)
        
        return is_feasible, max_cap, collision_prob
    
    def generate_unique_paths(self, count: int, depth: int, 
                             breadth: int, chaos: float) -> List[str]:
        """
        Generate exactly n unique paths using rejection sampling with 
        exponential backoff and theoretical guarantees.
        
        Algorithm (Principle of Deferred Decisions):
        1. While |P| < n and attempts < max_attempts:
           a. Sample root theme t_0 ~ Uniform(themes)
           b. For i = 1 to D:
              - Sample t_i ~ P(t_i | t_{i-1}) from transition kernel
              - Sample word w_i ~ Uniform(Σ_{t_i})
              - With probability (1-chaos), accept; else resample t_i uniformly
           c. Construct path p = w_1/w_2/.../w_k where k ~ Uniform[1, D]
           d. If p ∉ P: add to P
        
        Complexity: 
        - Expected O(n · D / (1 - collision_prob)) time
        - Space O(n · D) for storage
        
        Args:
            count: Target number of paths N
            depth: Maximum depth D
            breadth: Branching factor b (max children per node)
            chaos: Entropy injection α ∈ [0,1] (probability of uniform resampling)
            
        Returns:
            Sorted list of unique paths.
        """
        # Validate inputs
        count = max(0, count)
        depth = max(1, min(depth, 20))  # Hard limit for safety
        breadth = max(1, min(breadth, 15))
        chaos = max(0.0, min(1.0, chaos))
        
        # Check feasibility with probabilistic bounds
        feasible, max_cap, collision_prob = self.verify_feasibility(count, depth, breadth)
        
        if not feasible:
            if collision_prob >= 0.5:
                print(f"Warning: Collision probability {collision_prob:.2%} too high. "
                      f"Reducing count from {count} to {max_cap // 2} for safety.")
                count = max(1, max_cap // 2)
            else:
                print(f"Warning: Requested {count} paths exceeds capacity {max_cap}. "
                      f"Truncating to {max_cap}.")
                count = min(count, max_cap)
        
        # Use graph-based generation for structural integrity (backwards compatible)
        # but wrap with additional verification and retry logic
        
        # Local import to avoid circular dependency issues
        try:
            graph = LabyrinthGraph(depth, breadth, chaos, self.measure)
        except NameError:
            # Fallback if LabyrinthGraph not available - pure combinatorial generation
            return self._generate_pure_combinatorial(count, depth, breadth, chaos)
        
        paths: Set[str] = set()
        attempts = 0
        max_attempts = count * 20  # Prevent infinite loops
        
        # Adaptive strategy: if collision probability high, use tree traversal
        # otherwise use random sampling
        if collision_prob > 0.1:
            # Use rigorous tree enumeration with pruning
            paths = self._generate_tree_enumeration(count, depth, breadth, chaos)
        else:
            # Use standard graph generation with verification
            while len(paths) < count and attempts < max_attempts:
                batch_size = min(count - len(paths), 100)
                batch = graph.generate(batch_size)
                
                new_paths = set(batch) - paths
                paths.update(new_paths)
                
                attempts += batch_size
                
                # If stuck (diminishing returns), switch strategy
                if len(new_paths) < batch_size * 0.5 and attempts > count * 5:
                    break
        
        # If still short, fill with deterministic enumeration
        if len(paths) < count:
            remaining = count - len(paths)
            extra = self._generate_tree_enumeration(remaining, depth, breadth, chaos, exclude=paths)
            paths.update(extra)
        
        # Verify uniqueness (set property) - mathematical invariant
        if len(paths) != len(set(paths)):
            # This should never happen by construction
            raise RuntimeError(f"Collision detected: generated {len(paths)} items with "
                             f"{len(set(paths))} unique values")
        
        return sorted(list(paths))
    
    def _generate_tree_enumeration(self, count: int, depth: int, 
                                   breadth: int, chaos: float,
                                   exclude: Optional[Set[str]] = None) -> Set[str]:
        """
        Deterministic tree traversal with randomized child ordering.
        Guarantees no collisions by construction (tree traversal).
        
        Uses BFS with random child selection to explore the tree space
        without replacement.
        """
        if exclude is None:
            exclude = set()
        
        results: Set[str] = set()
        
        # Root nodes: all possible starting themes
        roots = list(self.themes)
        random.shuffle(roots)
        
        # BFS frontier: (current_path, current_theme, current_depth)
        frontier = [(theme.value, theme, 0) for theme in roots]
        random.shuffle(frontier)
        
        while frontier and len(results) < count:
            # Randomized BFS to ensure variety
            idx = random.randint(0, len(frontier) - 1)
            frontier[idx], frontier[-1] = frontier[-1], frontier[idx]
            path, theme, d = frontier.pop()
            
            if d >= depth:
                continue
            
            # Generate children according to breadth limit
            children_to_generate = min(breadth, 3 + int(breadth * (1 - d/depth)))
            
            for _ in range(children_to_generate):
                # Theme transition
                if random.random() < chaos:
                    next_theme = random.choice(self.themes)
                else:
                    trans = self._restricted_transition.get(theme, {})
                    if trans:
                        next_theme = random.choices(list(trans.keys()), 
                                                   weights=list(trans.values()))[0]
                    else:
                        next_theme = theme
                
                # Sample semantic element
                if next_theme in self.measure.Ω:
                    categories = list(self.measure.Ω[next_theme].keys())
                    cat = random.choice(categories)
                    elements = self.measure.Ω[next_theme][cat]
                    if elements:
                        elem = random.choice(elements)
                        new_path = f"{path}/{elem.symbol}" if path else elem.symbol
                        
                        if new_path not in exclude:
                            results.add(new_path)
                            if len(results) >= count:
                                return results
                            
                            if d + 1 < depth:
                                frontier.append((new_path, next_theme, d + 1))
        
        return results
    
    def _generate_pure_combinatorial(self, count: int, depth: int,
                                     breadth: int, chaos: float) -> List[str]:
        """
        Fallback generation when LabyrinthGraph unavailable.
        Uses direct combinatorial construction.
        """
        paths = set()
        attempts = 0
        max_attempts = count * 50
        
        while len(paths) < count and attempts < max_attempts:
            # Build path component by component
            current_theme = random.choice(self.themes)
            components = []
            
            actual_depth = random.randint(1, depth)
            
            for d in range(actual_depth):
                # Get available elements for current theme
                if current_theme not in self.measure.Ω:
                    break
                
                categories = list(self.measure.Ω[current_theme].keys())
                if not categories:
                    break
                
                cat = random.choice(categories)
                elements = self.measure.Ω[current_theme][cat]
                if not elements:
                    break
                
                elem = random.choice(elements)
                components.append(elem.symbol)
                
                # Transition for next iteration
                if d < actual_depth - 1:
                    if random.random() < chaos:
                        current_theme = random.choice(self.themes)
                    else:
                        trans = self._restricted_transition.get(current_theme, {})
                        if trans:
                            current_theme = random.choices(list(trans.keys()),
                                                          weights=list(trans.values()))[0]
            
            if components:
                path = "/".join(components)
                if path not in paths:
                    paths.add(path)
            
            attempts += 1
        
        return sorted(list(paths))


# =============================================================================
# ENTROPY & INFORMATION THEORY
# =============================================================================

def calculate_kolmogorov_complexity_estimate(path: str) -> float:
    """
    Estimate Kolmogorov complexity K(x) using algorithmic information theory.
    
    Since K(x) is uncomputable, we approximate using normalized metrics:
    - c_LZ(x): Lempel-Ziv complexity (dictionary parsing ratio)
    - H(x): Shannon entropy (character distribution uncertainty)
    - ρ(x): Compression ratio via run-length encoding
    
    The estimate combines these as:
    K̂(x) = 0.4·c_LZ(x) + 0.3·H(x)/H_max + 0.3·ρ(x)
    
    Args:
        path: Filesystem path string (e.g., "dungeon/cell/block_7")
        
    Returns:
        Float in [0.0, 1.0] where:
        - 0.0: Highly regular/compressible (e.g., "a/a/a/a")
        - 1.0: Maximal complexity/randomness (e.g., "x9#kL/mQ2/vZ!")
        
    Note: This implementation corrects previous versions where return values
    were semantically inverted (high values indicated simplicity).
    """
    if not path or path.strip('/') == '':
        return 0.0
    
    clean_path = path.strip('/')
    parts = clean_path.split('/')
    n_parts = len(parts)
    
    # Metric 1: Lempel-Ziv complexity (compression dictionary size)
    def lz_complexity(s: str) -> float:
        """Calculate normalized LZ76 complexity."""
        n = len(s)
        if n <= 1:
            return 0.0
        
        i, complexity = 0, 0
        history = set()
        
        while i < n:
            # Find longest substring starting at i seen before in window
            max_match = 0
            window_start = max(0, i - 100)  # Sliding window of 100 chars
            
            for length in range(1, min(n - i + 1, 50)):  # Max match 50
                substring = s[i:i+length]
                found = False
                for j in range(window_start, i):
                    if s[j:j+length] == substring:
                        found = True
                        break
                if found:
                    max_match = length
                else:
                    break
            
            if max_match == 0:
                history.add(s[i])
                i += 1
            else:
                history.add(s[i:i+max_match+1] if i+max_match < n else s[i:])
                i += max_match
            
            complexity += 1
            
            # Prevent infinite loops on pathological input
            if complexity > 2 * n:
                return 1.0
        
        # Normalize: random string has complexity ≈ n/log(n)
        if n > 2:
            return min(1.0, complexity / (n / log2(n)))
        return complexity / n if n > 0 else 0.0
    
    # Metric 2: Shannon entropy (information density)
    def shannon_entropy(s: str) -> float:
        """Calculate normalized Shannon entropy H(X)/log₂(|Σ|)."""
        if not s:
            return 0.0
        
        freq = {}
        for c in s:
            freq[c] = freq.get(c, 0) + 1
        
        n = len(s)
        entropy = -sum((count/n) * log2(count/n) for count in freq.values())
        
        # Normalize by maximum possible entropy (log of alphabet size)
        # Filesystem paths typically use [a-z0-9_/] ≈ 37 chars
        max_entropy = log2(max(37, len(freq)))
        return entropy / max_entropy if max_entropy > 0 else 0.0
    
    # Metric 3: Structural periodicity (path level)
    def structural_complexity(components: list) -> float:
        """Measure directory hierarchy complexity."""
        m = len(components)
        if m <= 1:
            return lz_complexity(components[0]) if m == 1 else 0.0
        
        # Variety ratio (unique/total)
        unique = len(set(components))
        variety = unique / m
        
        # Detect periodic patterns (e.g., a/b/a/b vs a/b/c/d)
        if unique < m:  # Only check if repetitions exist
            # Count pattern violations
            pattern_score = 0.0
            for period in range(1, min(m, 6)):  # Check periods 1-5
                matches = sum(1 for i in range(m-period) 
                            if components[i] == components[i+period])
                similarity = matches / (m - period)
                pattern_score = max(pattern_score, similarity)
            
            # High pattern similarity = low complexity
            return variety * (1.0 - pattern_score * 0.5)
        
        return variety
    
    # Combine metrics with depth-dependent weighting
    string_complexity = 0.5 * lz_complexity(clean_path) + 0.5 * shannon_entropy(clean_path)
    
    if n_parts == 1:
        return string_complexity
    
    # For hierarchical paths, weight structure vs content
    struct_complexity = structural_complexity(parts)
    depth_weight = min(1.0, n_parts / 8.0)  # Asymptotic weight for deep paths
    
    # Blend: deeper paths weight structural complexity more
    estimate = (1.0 - depth_weight) * string_complexity + depth_weight * struct_complexity
    
    return max(0.0, min(1.0, estimate))


def verify_theorematic_coherence(
    paths: List[str], 
    expected_themes: List[SemanticAlphabet],
    measure_space: Optional[SemanticMeasureSpace] = None
) -> float:
    """
    Verify that generated paths satisfy thematic coherence theorem.
    
    Theorem: For any path p = (v₁, v₂, ..., vₙ), the sequence of themes
    θ(v₁), θ(v₂), ..., θ(vₙ) forms a Markov chain with transition
    probabilities defined by the semantic measure space.
    
    Mathematically, we verify that the empirical transition frequencies
    converge to the theoretical Markov kernel M where M[i,j] = P(θ(v_{k+1}) = j | θ(v_k) = i).
    
    Args:
        paths: List of generated paths (vertex sequences)
        expected_themes: Subset of themes to validate against (if empty, accepts all)
        measure_space: Probability space (Ω, F, P) containing transition kernel.
                      If None, constructs default space (backwards compatibility).
    
    Returns:
        Coherence score ∈ [0, 1] representing the average log-likelihood ratio
        of observed transitions under the Markov model vs uniform random.
        Score = 1.0 indicates perfect adherence to the Markov kernel.
        Score = 0.0 indicates complete deviation or no valid transitions.
    """
    if not paths:
        return 0.0
    
    # Initialize measure space if not provided (maintains backwards compatibility)
    if measure_space is None:
        measure_space = SemanticMeasureSpace()
    
    # Build reverse index: symbol -> theme for O(1) lookup
    symbol_to_theme: Dict[str, SemanticAlphabet] = {}
    for theme, categories in measure_space.Ω.items():
        for category, elements in categories.items():
            for elem in elements:
                symbol_to_theme[elem.symbol] = theme
    
    # Modifiers used in composition (from _generate_modifier)
    modifier_prefixes = {
        "collapsed", "flooded", "burning", "frozen", "cursed", "haunted",
        "sealed", "forbidden", "defiled", "abandoned", "ruined", "crumbling",
        "overgrown", "submerged", "scorched", "poisoned", "decaying", "shattered",
        "twisted", "corrupted", "ancient", "forgotten", "long_lost", "once_was",
        "the_old", "former", "historic", "primordial", "archaic", "timeworn",
        "bygone", "ruined_era", "of_the_first_age", "pre_collapse", "post_siege",
        "during_the_plague", "first", "second", "third", "the_fourth", 
        "fifth_and_final", "seventh", "thirteenth", "the_last", "zero", "nine",
        "of_the_dead_king", "of_the_black_order", "of_the_nameless_god",
        "of_the_forsaken", "of_the_damned", "of_the_wretched", "of_iron_and_ash",
        "of_the_flesh_cult", "belonging_to_none", "of_the_shadow_lords",
        "of_the_fallen_empire", "of_the_blind_prophet", "of_the_carrion_throne",
        "of_the_undying_tyrant", "of_the_lost_faith", "inner", "outer", 
        "lower", "upper", "deep", "shallow", "central", "peripheral", 
        "hidden", "exposed", "north", "south", "east", "west", "left", 
        "right", "above", "below"
    }
    
    def extract_theme(component: str) -> Optional[SemanticAlphabet]:
        """
        Extract theme from path component handling composite names.
        Attempts exact match, then progressively strips modifiers.
        """
        if not component:
            return None
            
        # Direct lookup
        if component in symbol_to_theme:
            return symbol_to_theme[component]
        
        # Handle composite: modifier_symbol or modifier_descriptor_symbol
        parts = component.split('_')
        
        # Try stripping increasing numbers of prefix components
        for i in range(len(parts)):
            candidate = '_'.join(parts[i:])
            if candidate in symbol_to_theme:
                return symbol_to_theme[candidate]
            
            # Also try: if any single part matches (for simple modifiers)
            if i < len(parts) - 1:
                for part in parts[i:]:
                    if part in symbol_to_theme:
                        return symbol_to_theme[part]
        
        # Fuzzy matching: find theme with longest common substring
        # (Fallback for heavily modified or corrupted names)
        best_match = None
        best_len = 0
        for symbol, theme in symbol_to_theme.items():
            # Check if symbol is substring of component
            if symbol in component and len(symbol) > best_len:
                best_len = len(symbol)
                best_match = theme
        
        return best_match
    
    # Convert expected_themes to set for O(1) lookup
    expected_set = set(expected_themes) if expected_themes else None
    
    total_coherence = 0.0
    valid_paths = 0
    empirical_transitions: Dict[Tuple[SemanticAlphabet, SemanticAlphabet], int] = defaultdict(int)
    total_transitions = 0
    
    for path in paths:
        components = path.split('/')
        if len(components) < 2:
            # Single vertex: trivially coherent (no transitions to violate Markov property)
            total_coherence += 1.0
            valid_paths += 1
            continue
        
        # Extract theme sequence θ(v₁), ..., θ(vₙ)
        theme_sequence = []
        for comp in components:
            theme = extract_theme(comp)
            if theme is not None:
                theme_sequence.append(theme)
            else:
                # Unknown theme - mark as None for skipping
                theme_sequence.append(None)
        
        # Calculate path coherence via transition probabilities
        path_score = 0.0
        valid_transitions = 0
        
        for i in range(len(theme_sequence) - 1):
            curr = theme_sequence[i]
            next_t = theme_sequence[i + 1]
            
            # Skip if either theme is unknown
            if curr is None or next_t is None:
                continue
            
            # If expected themes specified, verify both in expected set
            if expected_set is not None:
                if curr not in expected_set or next_t not in expected_set:
                    # Unexpected theme reduces coherence
                    continue
            
            # Get theoretical transition probability from Markov kernel
            if curr in measure_space.transition_kernel:
                theoretical_prob = measure_space.transition_kernel[curr].get(next_t, 0.0)
                
                if theoretical_prob > 0:
                    # Use log-likelihood to handle small probabilities gracefully
                    # Normalize by uniform probability (1/|alphabet|) for comparison
                    uniform_prob = 1.0 / len(measure_space.transition_kernel)
                    log_ratio = log2(theoretical_prob / uniform_prob) if uniform_prob > 0 else 0
                    
                    # Convert back to [0,1] range using sigmoid-like normalization
                    # Score = 1 if prob = 1, Score = 0 if prob = uniform (random)
                    normalized_score = (theoretical_prob - uniform_prob) / (1.0 - uniform_prob)
                    normalized_score = max(0.0, min(1.0, normalized_score))
                    
                    path_score += normalized_score
                    valid_transitions += 1
                    
                    # Track empirical distribution
                    empirical_transitions[(curr, next_t)] += 1
                    total_transitions += 1
        
        if valid_transitions > 0:
            total_coherence += path_score / valid_transitions
            valid_paths += 1
        else:
            # No valid transitions found in path (all unknown or single component)
            total_coherence += 0.0
            valid_paths += 1
    
    if valid_paths == 0:
        return 0.0
    
    global_coherence = total_coherence / valid_paths
    
    # Statistical diagnostics (optional, for rigorous verification)
    if total_transitions > 0 and len(empirical_transitions) > 0:
        print(f"\n  [Thematic Coherence Analysis]")
        print(f"  Total transitions analyzed: {total_transitions}")
        print(f"  Unique transition types: {len(empirical_transitions)}")
        
        # Chi-square test approximation for Markov property
        chi_sq = 0.0
        for (t1, t2), observed in empirical_transitions.items():
            if t1 in measure_space.transition_kernel:
                expected_prob = measure_space.transition_kernel[t1].get(t2, 0.0)
                expected_count = total_transitions * expected_prob
                if expected_count > 0:
                    chi_sq += ((observed - expected_count) ** 2) / expected_count
        
        print(f"  Pearson χ² statistic: {chi_sq:.4f}")
        print(f"  Coherence score: {global_coherence:.4f}")
        
        # Top 3 most frequent transitions
        top_trans = sorted(empirical_transitions.items(), 
                          key=lambda x: x[1], reverse=True)[:3]
        print(f"  Dominant transitions:")
        for (t1, t2), count in top_trans:
            emp_prob = count / total_transitions
            the_prob = measure_space.transition_kernel[t1].get(t2, 0.0)
            print(f"    {t1.name}→{t2.name}: {emp_prob:.3f} (theory: {the_prob:.3f})")
    
    return global_coherence

# =============================================================================
# MAIN EXECUTION
# =============================================================================

def map_keywords_to_themes(keywords: List[str]) -> List[SemanticAlphabet]:
    """
    Map user keywords to formal semantic alphabet using fuzzy logic.
    
    μ_keyword(theme) = similarity(keyword, theme) ∈ [0,1]
    """
    keyword_map = {
        "city": SemanticAlphabet.CITY, "town": SemanticAlphabet.CITY,
        "urban": SemanticAlphabet.CITY, "streets": SemanticAlphabet.CITY,
        "dungeon": SemanticAlphabet.DUNGEON, "prison": SemanticAlphabet.DUNGEON,
        "cave": SemanticAlphabet.DUNGEON, "tunnel": SemanticAlphabet.DUNGEON,
        "hell": SemanticAlphabet.HELL, "inferno": SemanticAlphabet.HELL,
        "demon": SemanticAlphabet.HELL, "abyss": SemanticAlphabet.HELL,
        "labyrinth": SemanticAlphabet.LABYRINTH, "maze": SemanticAlphabet.LABYRINTH,
        "trap": SemanticAlphabet.LABYRINTH, "corridor": SemanticAlphabet.LABYRINTH,
        "fortress": SemanticAlphabet.FORTRESS, "castle": SemanticAlphabet.FORTRESS,
        "siege": SemanticAlphabet.FORTRESS, "war": SemanticAlphabet.FORTRESS,
        "plague": SemanticAlphabet.PLAGUE, "disease": SemanticAlphabet.PLAGUE,
        "rot": SemanticAlphabet.PLAGUE, "undead": SemanticAlphabet.PLAGUE,
        "cult": SemanticAlphabet.CULT, "ritual": SemanticAlphabet.CULT,
        "sacrifice": SemanticAlphabet.CULT, "occult": SemanticAlphabet.CULT,
        "graveyard": SemanticAlphabet.GRAVEYARD, "cemetery": SemanticAlphabet.GRAVEYARD,
        "tomb": SemanticAlphabet.GRAVEYARD, "burial": SemanticAlphabet.GRAVEYARD,
    }
    
    themes = set()
    for kw in keywords:
        kw_lower = kw.lower()
        if kw_lower in keyword_map:
            themes.add(keyword_map[kw_lower])
        else:
            # Partial matching
            for key, theme in keyword_map.items():
                if key in kw_lower or kw_lower in key:
                    themes.add(theme)
                    break
    
    # Default to full alphabet if no matches
    if not themes:
        themes = set(SemanticAlphabet)
    
    return list(themes)


def main():
    parser = argparse.ArgumentParser(
        description="Mathematically rigorous labyrinth generator using graph theory "
                    "and measure-theoretic probability.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Mathematical Foundations:
  • Graph Theory: Generation of DAGs G=(V,E) with bounded depth/degree
  • Measure Theory: Probability space (Ω, F, P) over semantic elements
  • Markov Chains: Thematic transitions with stochastic kernel
  • Information Theory: Shannon entropy H(X) of generated structures
  • Combinatorics: Bounded enumeration without replacement

Constraints enforced:
  1. Acyclicity: G is a DAG (no cycles)
  2. Uniqueness: |V| unique paths (no collisions)
  3. Bounded complexity: depth ≤ D, deg⁺(v) ≤ B
  4. Thematic coherence: Markov property on theme transitions
        """,
    )
    
    parser.add_argument("keywords", nargs="+", 
                       help="Semantic keywords to seed the measure space")
    parser.add_argument("--base", "-b", default="./labyrinth",
                       help="Base directory (root of graph)")
    parser.add_argument("--count", "-c", type=int, default=25,
                       help="Target number of vertices |V|")
    parser.add_argument("--depth", "-d", type=int, default=5,
                       help="Maximum depth D (graph diameter bound)")
    parser.add_argument("--breadth", "-w", type=int, default=4,
                       help="Maximum out-degree (branching factor)")
    parser.add_argument("--chaos", "-x", type=float, default=0.3,
                       help="Entropy injection factor α ∈ [0,1]")
    parser.add_argument("--seed", "-s", type=int, default=None,
                       help="Random seed for reproducibility")
    parser.add_argument("--dry-run", "-n", action="store_true",
                       help="Simulate without file system mutation")
    parser.add_argument("--verify", action="store_true",
                       help="Verify graph properties (acyclicity, connectivity)")
    parser.add_argument("--export", "-e", default=None,
                       help="Export graph to shell script")
    
    args = parser.parse_args()
    
    # Set random seed for reproducibility
    if args.seed is not None:
        random.seed(args.seed)
    
    # Validate parameters
    count = max(1, args.count)
    depth = max(1, min(args.depth, TopologicalConstraint.MAX_DEPTH))
    breadth = max(1, min(args.breadth, TopologicalConstraint.MAX_BRANCHING_FACTOR))
    chaos = max(0.0, min(1.0, args.chaos))
    
    print(f"\n[MATHEMATICAL SPECIFICATION]")
    print(f"  Target vertices |V| = {count}")
    print(f"  Maximum depth D = {depth}")
    print(f"  Branching factor b = {breadth}")
    print(f"  Entropy factor α = {chaos}")
    if args.seed:
        print(f"  Random seed = {args.seed}")
    
    # Initialize measure space (Ω, F, P)
    print("\n[CONSTRUCTING MEASURE SPACE]")
    measure = SemanticMeasureSpace()
    
    # Map keywords to themes
    themes = map_keywords_to_themes(args.keywords)
    print(f"  Active themes: {[t.name for t in themes]}")
    
    # Calculate theoretical capacity
    combinatorial = CombinatorialGenerator(measure, themes)
    capacity = combinatorial.calculate_capacity(depth, breadth)
    print(f"  Theoretical capacity C(D,B) = {capacity}")
    print(f"  Requested |V| = {count} (utilization: {count/capacity:.2%})")
    
    # Verify feasibility
    feasible, max_p = combinatorial.verify_feasibility(count, depth, breadth)
    if not feasible:
        print(f"  WARNING: Exceeds capacity. Truncating to {max_p}.")
        count = max_p
    
    # Generate labyrinth (graph construction)
    print("\n[GRAPH CONSTRUCTION]")
    print(f"  Generating DAG G = (V, E)...")
    
    paths = combinatorial.generate_unique_paths(count, depth, breadth, chaos)
    
    print(f"  Generated |V| = {len(paths)} vertices")
    print(f"  Path space entropy H ≈ {log2(len(paths)):.2f} bits")
    
    # Verify properties if requested
    if args.verify:
        print("\n[FORMAL VERIFICATION]")
        # Reconstruct graph for verification
        graph = LabyrinthGraph(depth, breadth, chaos, measure)
        for path in paths:
            # Parse path and add to graph (simplified)
            parts = path.split('/')
            for i in range(len(parts)):
                subpath = '/'.join(parts[:i+1])
                if subpath not in graph.vertices:
                    depth_i = i
                    theme = random.choice(themes)  # Approximation
                    node = LabyrinthNode(
                        id=hash(subpath),
                        path=subpath,
                        depth=depth_i,
                        theme=theme
                    )
                    graph.vertices[subpath] = node
        
        is_dag = graph.verify_acyclicity()
        print(f"  DAG property: {'VERIFIED' if is_dag else 'FAILED'}")
        
        shannon_entropy = graph.calculate_shannon_entropy()
        print(f"  Shannon entropy H(X) = {shannon_entropy:.4f} bits")
    
    # Export or create
    if args.dry_run:
        print(f"\n[DRY RUN] Would create {len(paths)} directories:")
        for i, p in enumerate(list(paths)[:10], 1):
            print(f"  {i}. {p}")
        if len(paths) > 10:
            print(f"  ... and {len(paths) - 10} more")
    else:
        print(f"\n[FILE SYSTEM MUTATION]")
        base_path = os.path.abspath(args.base)
        os.makedirs(base_path, exist_ok=True)
        
        created = 0
        failed = 0
        
        for path in paths:
            full_path = os.path.join(base_path, path)
            try:
                os.makedirs(full_path, exist_ok=False)
                created += 1
            except FileExistsError:
                failed += 1
            except Exception as e:
                failed += 1
        
        print(f"  Created: {created}")
        print(f"  Failed:  {failed}")
    
    # Export shell script if requested
    if args.export:
        with open(args.export, 'w') as f:
            f.write("#!/bin/bash\n")
            f.write(f"# Rigorous Labyrinth: |V|={len(paths)}, D={depth}, b={breadth}\n")
            f.write(f'BASE="{os.path.abspath(args.base)}"\n')
            for path in paths:
                f.write(f'mkdir -p "$BASE/{path}"\n')
        os.chmod(args.export, 0o755)
        print(f"\n[EXPORT] Shell script: {args.export}")
    
    print("\n[DONE]")


if __name__ == "__main__":
    main()
